
services:
###> doctrine/doctrine-bundle ###
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - database
    environment:
        DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}
    volumes:
        - ./:/app:rw
        - caddy_data:/data
        - caddy_config:/config

    networks:
        - hexagonal
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
        - hexagonal

volumes:
  database_data:
  caddy_data:
  caddy_config:
networks:
  hexagonal:
    driver: bridge